# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-05 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billedproducts',
            name='unit',
            field=models.CharField(default='KG', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 5, 21, 8, 7, 149577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (12, 12), (18, 18)], default=5),
        ),
        migrations.AlterField(
            model_name='productrate',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('Pc', 'Pc'), ('Pkt', 'Pkt'), ('Ltr', 'Ltr'), ('Tin', 'Tin'), ('Bottle', 'Bottle'), ('Metre', 'Metre'), ('Box', 'Box')], default='KG', max_length=10),
        ),
    ]
