# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180706_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 6, 49, 28, 353499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 6, 49, 28, 353499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='seller_address',
            field=models.CharField(max_length=100),
        ),
    ]
