# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180706_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproduct',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('Pc', 'Pc'), ('Pkt', 'Pkt'), ('Ltr', 'Ltr'), ('Tin', 'Tin'), ('Bottle', 'Bottle'), ('Metre', 'Metre'), ('Box', 'Box')], default='KG', max_length=10),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 13, 6, 18, 15265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 13, 6, 18, 15265, tzinfo=utc)),
        ),
    ]
