# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180706_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Summary',
                'verbose_name_plural': 'Purchase Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounts.purchasedproduct',),
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 21, 43, 38, 373081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 21, 43, 38, 373081, tzinfo=utc)),
        ),
    ]
