# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 22:14
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180707_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 22, 14, 40, 249847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='GSTIN',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 22, 14, 40, 249847, tzinfo=utc)),
        ),
    ]
