# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180707_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='invoice_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='po_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 10, 14, 19, 51, 229222, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='bills',
            name='po_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 10, 14, 19, 51, 229222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 10, 14, 19, 51, 229222, tzinfo=utc)),
        ),
    ]
