# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-05 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180801_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 22, 21, 51, 885140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_number',
            field=models.IntegerField(default=0, unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='po_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 22, 21, 51, 885140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productrate',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('Pcs', 'Pcs'), ('Pkt', 'Pkt'), ('Ltr', 'Ltr'), ('Tin', 'Tin'), ('Bottle', 'Bottle'), ('Metre', 'Metre'), ('Box', 'Box')], default='KG', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 22, 21, 51, 885140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('Pcs', 'Pcs'), ('Pkt', 'Pkt'), ('Ltr', 'Ltr'), ('Tin', 'Tin'), ('Bottle', 'Bottle'), ('Metre', 'Metre'), ('Box', 'Box')], default='KG', max_length=10),
        ),
    ]
