# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-06 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190706_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 6, 1, 51, 27, 633881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_number',
            field=models.IntegerField(default=0, unique_for_year='po_date'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='po_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 6, 1, 51, 27, 633881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 6, 1, 51, 27, 633881, tzinfo=utc)),
        ),
    ]
